//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerData {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerData.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Customer ähnelt.
        /// </summary>
        internal static string addCustomer {
            get {
                return ResourceManager.GetString("addCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance ähnelt.
        /// </summary>
        internal static string ballance {
            get {
                return ResourceManager.GetString("ballance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate ID ähnelt.
        /// </summary>
        internal static string btnGenerateID {
            get {
                return ResourceManager.GetString("btnGenerateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Customer ähnelt.
        /// </summary>
        internal static string changeCustomer {
            get {
                return ResourceManager.GetString("changeCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Language ähnelt.
        /// </summary>
        internal static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer Number ähnelt.
        /// </summary>
        internal static string customerNumber {
            get {
                return ResourceManager.GetString("customerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data stored ähnelt.
        /// </summary>
        internal static string dadaSaved {
            get {
                return ResourceManager.GetString("dadaSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail Adress ähnelt.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email already exists. Customer not added. ähnelt.
        /// </summary>
        internal static string emailExists {
            get {
                return ResourceManager.GetString("emailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty Database! No Customers found. Storeing data canceled ähnelt.
        /// </summary>
        internal static string emptyDatabase {
            get {
                return ResourceManager.GetString("emptyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File was empty! No Customer added. ähnelt.
        /// </summary>
        internal static string emptyFile {
            get {
                return ResourceManager.GetString("emptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer couldn&apos;t changed ähnelt.
        /// </summary>
        internal static string erCustNotChanged {
            get {
                return ResourceManager.GetString("erCustNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email already exists. ähnelt.
        /// </summary>
        internal static string erEmailexists {
            get {
                return ResourceManager.GetString("erEmailexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email Adress not valid! ähnelt.
        /// </summary>
        internal static string erEmialNotValid {
            get {
                return ResourceManager.GetString("erEmialNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer ID not found. ähnelt.
        /// </summary>
        internal static string erIDNotFound {
            get {
                return ResourceManager.GetString("erIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer Id not found. Booking Canceled. ähnelt.
        /// </summary>
        internal static string erIDNotFound_ButOpen {
            get {
                return ResourceManager.GetString("erIDNotFound_ButOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To less Input. ähnelt.
        /// </summary>
        internal static string erLessInput {
            get {
                return ResourceManager.GetString("erLessInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ID inserted ähnelt.
        /// </summary>
        internal static string erNoID {
            get {
                return ResourceManager.GetString("erNoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer ID not found. Change not possible. ähnelt.
        /// </summary>
        internal static string erNoID_nochange {
            get {
                return ResourceManager.GetString("erNoID_nochange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter By ähnelt.
        /// </summary>
        internal static string filterby {
            get {
                return ResourceManager.GetString("filterby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name ähnelt.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Customer Data ähnelt.
        /// </summary>
        internal static string getCustomData {
            get {
                return ResourceManager.GetString("getCustomData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID already used. Customer not added. ähnelt.
        /// </summary>
        internal static string idUsed {
            get {
                return ResourceManager.GetString("idUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Name ähnelt.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Data ähnelt.
        /// </summary>
        internal static string loadData {
            get {
                return ResourceManager.GetString("loadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Make Booking ähnelt.
        /// </summary>
        internal static string makeBooking {
            get {
                return ResourceManager.GetString("makeBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No stored Data Found ähnelt.
        /// </summary>
        internal static string noStoredData {
            get {
                return ResourceManager.GetString("noStoredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password was not correct. ähnelt.
        /// </summary>
        internal static string passwordWrong {
            get {
                return ResourceManager.GetString("passwordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pay In ähnelt.
        /// </summary>
        internal static string payIn {
            get {
                return ResourceManager.GetString("payIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pay Out ähnelt.
        /// </summary>
        internal static string payOut {
            get {
                return ResourceManager.GetString("payOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Data ähnelt.
        /// </summary>
        internal static string saveData {
            get {
                return ResourceManager.GetString("saveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die corrupt Database, can&apos;t display data ähnelt.
        /// </summary>
        internal static string showCustomer {
            get {
                return ResourceManager.GetString("showCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By ähnelt.
        /// </summary>
        internal static string sortby {
            get {
                return ResourceManager.GetString("sortby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name is to short. ähnelt.
        /// </summary>
        internal static string tesxtNameToshort {
            get {
                return ResourceManager.GetString("tesxtNameToshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter Password ähnelt.
        /// </summary>
        internal static string textEnterPassword {
            get {
                return ResourceManager.GetString("textEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Email ähnelt.
        /// </summary>
        internal static string textInvalidEmail {
            get {
                return ResourceManager.GetString("textInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Customer ähnelt.
        /// </summary>
        internal static string titleAdd {
            get {
                return ResourceManager.GetString("titleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Booking ähnelt.
        /// </summary>
        internal static string titleBooking {
            get {
                return ResourceManager.GetString("titleBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Customer ähnelt.
        /// </summary>
        internal static string titleChange {
            get {
                return ResourceManager.GetString("titleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer handler ähnelt.
        /// </summary>
        internal static string titleMain {
            get {
                return ResourceManager.GetString("titleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entry Password ähnelt.
        /// </summary>
        internal static string titlePassword {
            get {
                return ResourceManager.GetString("titlePassword", resourceCulture);
            }
        }
    }
}
