//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerData {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class German {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal German() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerData.German", typeof(German).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunde hinzufügen ähnelt.
        /// </summary>
        internal static string addCustomer {
            get {
                return ResourceManager.GetString("addCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Betrag ähnelt.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballance ähnelt.
        /// </summary>
        internal static string ballance {
            get {
                return ResourceManager.GetString("ballance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunde Bearbeiten ähnelt.
        /// </summary>
        internal static string changeCustomer {
            get {
                return ResourceManager.GetString("changeCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ändern ähnelt.
        /// </summary>
        internal static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigen ähnelt.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunden Nummer ähnelt.
        /// </summary>
        internal static string customerNumber {
            get {
                return ResourceManager.GetString("customerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten gesichert. ähnelt.
        /// </summary>
        internal static string dadaSaved {
            get {
                return ResourceManager.GetString("dadaSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail Adresse ähnelt.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email existiert bereits. Kunde nicht hinzugefügt. ähnelt.
        /// </summary>
        internal static string emailExists {
            get {
                return ResourceManager.GetString("emailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leere Datenbank! Kein Kunde gefunden. Datensicherung abgebrochen. ähnelt.
        /// </summary>
        internal static string emptyDatabase {
            get {
                return ResourceManager.GetString("emptyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leeres File!keinKunde hinzugefügt. ähnelt.
        /// </summary>
        internal static string emptyFile {
            get {
                return ResourceManager.GetString("emptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunde konnte nicht geändert werden. ähnelt.
        /// </summary>
        internal static string erCustNotChanged {
            get {
                return ResourceManager.GetString("erCustNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email exisitert bereits. ähnelt.
        /// </summary>
        internal static string erEmailexists {
            get {
                return ResourceManager.GetString("erEmailexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email nicht gültig. ähnelt.
        /// </summary>
        internal static string erEmialNotValid {
            get {
                return ResourceManager.GetString("erEmialNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunden ID nicht gefunden ähnelt.
        /// </summary>
        internal static string erIDNotFound {
            get {
                return ResourceManager.GetString("erIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunden ID nicht gefunden. Zahlung abgebrochen. ähnelt.
        /// </summary>
        internal static string erIDNotFound_ButOpen {
            get {
                return ResourceManager.GetString("erIDNotFound_ButOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eingabe zu kurz. ähnelt.
        /// </summary>
        internal static string erLessInput {
            get {
                return ResourceManager.GetString("erLessInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die keine ID eingegeben ähnelt.
        /// </summary>
        internal static string erNoID {
            get {
                return ResourceManager.GetString("erNoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunden ID nicht gefunden. Änderung  nicht möglich. ähnelt.
        /// </summary>
        internal static string erNoID_nochange {
            get {
                return ResourceManager.GetString("erNoID_nochange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter nach: ähnelt.
        /// </summary>
        internal static string filterby {
            get {
                return ResourceManager.GetString("filterby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorname ähnelt.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunde anzeigen ähnelt.
        /// </summary>
        internal static string getCustomData {
            get {
                return ResourceManager.GetString("getCustomData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID existiert bereits. Kunde nicht hinzugefügt. ähnelt.
        /// </summary>
        internal static string idUsed {
            get {
                return ResourceManager.GetString("idUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachname ähnelt.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Daten ähnelt.
        /// </summary>
        internal static string loadData {
            get {
                return ResourceManager.GetString("loadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buchung durchführen ähnelt.
        /// </summary>
        internal static string makeBooking {
            get {
                return ResourceManager.GetString("makeBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine gespeichertenDaten gefunden. ähnelt.
        /// </summary>
        internal static string noStoredData {
            get {
                return ResourceManager.GetString("noStoredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort falsch. ähnelt.
        /// </summary>
        internal static string passwordWrong {
            get {
                return ResourceManager.GetString("passwordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einzahlen ähnelt.
        /// </summary>
        internal static string payIn {
            get {
                return ResourceManager.GetString("payIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auszahlen ähnelt.
        /// </summary>
        internal static string payOut {
            get {
                return ResourceManager.GetString("payOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten Sichern ähnelt.
        /// </summary>
        internal static string saveData {
            get {
                return ResourceManager.GetString("saveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehlerhafte Datenbank, Kunden können nicht angezeigt werden. ähnelt.
        /// </summary>
        internal static string showCustomer {
            get {
                return ResourceManager.GetString("showCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sortiere nach: ähnelt.
        /// </summary>
        internal static string sortby {
            get {
                return ResourceManager.GetString("sortby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ist zu kurz. ähnelt.
        /// </summary>
        internal static string tesxtNameToshort {
            get {
                return ResourceManager.GetString("tesxtNameToshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben sie das Passwort ein ähnelt.
        /// </summary>
        internal static string textEnterPassword {
            get {
                return ResourceManager.GetString("textEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültige Email. ähnelt.
        /// </summary>
        internal static string textInvalidEmail {
            get {
                return ResourceManager.GetString("textInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunde hinzufügen ähnelt.
        /// </summary>
        internal static string titleAdd {
            get {
                return ResourceManager.GetString("titleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buchung durchführen ähnelt.
        /// </summary>
        internal static string titleBooking {
            get {
                return ResourceManager.GetString("titleBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunde bearbeiten ähnelt.
        /// </summary>
        internal static string titleChange {
            get {
                return ResourceManager.GetString("titleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunden Verwaltung ähnelt.
        /// </summary>
        internal static string titleMain {
            get {
                return ResourceManager.GetString("titleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort eingeben ähnelt.
        /// </summary>
        internal static string titlePassword {
            get {
                return ResourceManager.GetString("titlePassword", resourceCulture);
            }
        }
    }
}
